# This file is retained solely for automated tooling to see we do automated
# dependency updates as not all such scanners recognize the use of Renovate.
# It also works around a limitation that Automatic dependency submission does
# not automatically detect .slnx files to signify the use of .NET in a repo.
#
# The NuGet entry below further addresses this limitation:
# https://docs.github.com/en/code-security/reference/supply-chain-security/automatic-dependency-submission#net-projects
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: yearly
