include:
  - project: 'ci-cd/templates'
    ref: master
    file: '/prodsec/.oss-scan.yml'

stages:
  - build
  - fossa-scan

build:
  stage: build
  image: "${DOCKER_MCR_REPO}/dotnet/sdk:9.0.102-bookworm-slim"
  script:
    - '/build.sh Restore'
    - '/build.sh BuildNugetPackage'
  artifacts:
  # See https://github.com/fossas/fossa-cli/tree/51add543ca72390819a801d5ad434b6b562ebddb/docs/references/strategies/languages/dotnet
    name: "project-assets"
    paths:
      - "**/project.assets.json"
oss-scan:
  stage: fossa-scan
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  extends: .oss-scan
  dependencies:
    - build
