include:
  - project: 'ci-cd/templates'
    ref: master
    file: '/prodsec/.oss-scan.yml'

stages:
  - fossa-scan

oss-scan:
  stage: fossa-scan
  before_script:
    - apk add dotnet8-sdk dotnet9-sdk
    - /build.sh Compile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  extends: .oss-scan
