//------------------------------------------------------------------------------
// <auto-generated />
// Vendored from https://github.com/protobuf-net/protobuf-net/archive/refs/tags/2.4.8.zip
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;

namespace Splunk.OpenTelemetry.AutoInstrumentation.Vendors.ProtoBuf
{
    /// <summary>Specifies a method on the root-contract in an hierarchy to be invoked before serialization.</summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
#if !CF && !PORTABLE && !COREFX && !PROFILE259
    [ImmutableObject(true)]
#endif
    internal sealed class ProtoBeforeSerializationAttribute : Attribute { }

    /// <summary>Specifies a method on the root-contract in an hierarchy to be invoked after serialization.</summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
#if !CF && !PORTABLE && !COREFX && !PROFILE259
    [ImmutableObject(true)]
#endif
    internal sealed class ProtoAfterSerializationAttribute : Attribute { }

    /// <summary>Specifies a method on the root-contract in an hierarchy to be invoked before deserialization.</summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
#if !CF && !PORTABLE && !COREFX && !PROFILE259
    [ImmutableObject(true)]
#endif
    internal sealed class ProtoBeforeDeserializationAttribute : Attribute { }

    /// <summary>Specifies a method on the root-contract in an hierarchy to be invoked after deserialization.</summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
#if !CF && !PORTABLE && !COREFX && !PROFILE259
    [ImmutableObject(true)]
#endif
    internal sealed class ProtoAfterDeserializationAttribute : Attribute { }
}
