//------------------------------------------------------------------------------
// <auto-generated />
// Vendored from https://github.com/protobuf-net/protobuf-net/archive/refs/tags/2.4.8.zip
//------------------------------------------------------------------------------
using System;

namespace Splunk.OpenTelemetry.AutoInstrumentation.Vendors.ProtoBuf
{
    /// <summary>
    /// Indicates that a static member should be considered the same as though
    /// were an implicit / explicit conversion operator; in particular, this
    /// is useful for conversions that operator syntax does not allow, such as
    /// to/from interface types.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    internal class ProtoConverterAttribute : Attribute { }
}