//------------------------------------------------------------------------------
// <auto-generated />
// Vendored from https://github.com/protobuf-net/protobuf-net/archive/refs/tags/2.4.8.zip
//------------------------------------------------------------------------------
namespace Splunk.OpenTelemetry.AutoInstrumentation.Vendors.ProtoBuf.Meta
{
    /// <summary>
    /// Indiate the variant of the protobuf .proto DSL syntax to use
    /// </summary>
    internal enum ProtoSyntax
    {
        /// <summary>
        /// https://developers.google.com/protocol-buffers/docs/proto
        /// </summary>
        Proto2 = 0,
        /// <summary>
        /// https://developers.google.com/protocol-buffers/docs/proto3
        /// </summary>
        Proto3 = 1,
    }
}