//------------------------------------------------------------------------------
// <auto-generated />
// Vendored from https://github.com/protobuf-net/protobuf-net/archive/refs/tags/2.4.8.zip
//------------------------------------------------------------------------------
#if FEAT_COMPILER
namespace Splunk.OpenTelemetry.AutoInstrumentation.Vendors.ProtoBuf.Compiler
{
    internal delegate void ProtoSerializer(object value, ProtoWriter dest);
    internal delegate object ProtoDeserializer(object value, ProtoReader source);
}
#endif