name: validate-documentation

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/validate-documentation.yml'
    - '**.md'
    - '.lycheeignore'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/validate-documentation.yml'
    - '**.md'
    - '.lycheeignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
      with:
        fail: true
        args: "--threads 1 --max-concurrency 1 --verbose --no-progress './**/*.md' './**/*.html'"

    - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
      with:
        files: '**/*.md'

    - name: Install markdownlint-cli2
      run: npm install --global markdownlint-cli2@0.22.1

    - name: Run markdownlint-cli2
      run: markdownlint-cli2 '**/*.md' '!.github/**' '!lychee/out.md'
