name: validate-documentation

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/validate-documentation.yml'
    - '**.md'
    - '.lycheeignore'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/validate-documentation.yml'
    - '**.md'
    - '.lycheeignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
      with:
        fail: true
        args: "--threads 1 --max-concurrency 1 --verbose --no-progress './**/*.md' './**/*.html'"

    - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
      with:
        files: '**/*.md'

    - uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
      with:
        globs: '**/*.md;!.github/**;!lychee/out.md'
        separator: ';'
